# Generated by Django 3.2.5 on 2021-07-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='time_without_charge',
            field=models.CharField(max_length=255, verbose_name='Время работы с аккумулятора'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='video',
            field=models.CharField(max_length=255, verbose_name='Видеокарта'),
        ),
    ]
